DROP TABLE EMP_BOARDS CASCADE CONSTRAINTS;

CREATE TABLE EMP_BOARDS (
	   ID NUMBER NOT NULL
	 , TITLE VARCHAR2(100) NOT NULL
	 , CONTENT VARCHAR2(2000)
	 , EMPID NUMBER NOT NULL
	 , CREATEDATE DATE DEFAULT(SYSDATE)
	 , CONSTRAINT EMP_BOARD_ID_PK PRIMARY KEY (ID)
	 , CONSTRAINT EMP_BOARD_EMP_ID_FK FOREIGN KEY(EMPID) REFERENCES EMPLOYEES (EMPLOYEES_ID)
);

CREATE SEQUENCE EMP_BOARDS_SEQ NOCACHE;

INSERT INTO EMP_BOARDS VALUES(EMP_BARDOS_SEQ.NEXTVAL, '테스트 제목', '테스트 내용', 100, SYSDATE);


