/*
 * HR 데이터 정보 확인
 */

-- 직원 테이블
SELECT * FROM EMPLOYEES;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID = 100;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID > 100;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID != 100;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID <> 100;

-- 부서 테이블
SELECT * FROM DEPARTMENTS;
SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM DEPARTMENTS;

-- 직급 테이블
SELECT * FROM JOBS;

-- 국가 테이블
SELECT * FROM COUNTRIES;

-- 국가의 지역 테이블
SELECT * FROM LOCATIONS;

-- 대륙 정보 테이블
SELECT * FROM REGIONS;



-- 컬럼명에 별칭 부여
SELECT EMPLOYEE_ID AS "사번" 
	, FIRST_NAME "이름"
	, LAST_NAME 성
	, EMAIL "이메일 주소"
 FROM EMPLOYEES;
 
-- 컬럼과의 연산
SELECT EMPLOYEE_ID "사번"
	, LAST_NAME || ' ' || FIRST_NAME "성명"
	, SALARY * 12 || ' 달러' "연봉"
 FROM EMPLOYEES;
 

-- 조건절
SELECT EMPLOYEE_ID "사번"		-- 다음 SELECT (3번째 읽음) 
	, FIRST_NAME 
	, LAST_NAME 
	, EMAIL 
	, PHONE_NUMBER 
	, HIRE_DATE 
	, JOB_ID 
	, SALARY 
	, COMMISSION_PCT 
	, MANAGER_ID 
	, DEPARTMENT_ID 
  FROM EMPLOYEES			-- FROM 부터 읽음 (1번째 읽음)
 WHERE EMPLOYEE_ID > 200;	-- 다음 WHERE (2번째 읽음)
 							-- 실행 순서 FROM > WHERE > SELCET
 							-- ORDER BY HAVING 
 							-- GROUP BY HAVING 
 
 -- 조건절에서 사용하는 연산자
 -- AND, OR, IN, NOT, NOT IN, BETWEEN ... AND,
 -- LIKE, IS NULL, IS NOT NULL
SELECT * FROM EMPLOYEES
 WHERE EMPLOYEE_ID > 200
   AND SALARY >= 10000;
 
SELECT * FROM EMPLOYEES
 WHERE EMPLOYEE_ID > 200
	OR SALARY >= 10000;
   	
SELECT * FROM EMPLOYEES
 WHERE NOT EMPLOYEE_ID > 200;
 
SELECT * FROM EMPLOYEES
 WHERE NOT EMPLOYEE_ID > 200		-- 연산자 우선순위 모르겠으면 소괄호 (소괄호 먼저함)
	AND SALARY >= 10000;			-- NOT -> AND -> OR
 
	
SELECT * FROM EMPLOYEES
 WHERE EMPLOYEE_ID IN (200, 201, 202, 203);

SELECT * FROM EMPLOYEES
 WHERE EMPLOYEE_ID NOT IN (200, 201, 202, 203);
 
SELECT * FROM EMPLOYEES
 WHERE EMPLOYEE_ID BETWEEN 200 AND 203;

SELECT * FROM EMPLOYEES
 WHERE EMPLOYEE_ID NOT BETWEEN 200 AND 203;


SELECT * FROM EMPLOYEES
 WHERE JOB_ID LIKE 'AD%';	-- 뒤에 어떠한 내용이 들어가도 AD만 들어가면 포함 시켜서 찾아줌
 
SELECT * FROM EMPLOYEES	
 WHERE JOB_ID LIKE '%VP';
 
SELECT * FROM EMPLOYEES
 WHERE JOB_ID LIKE '%A%';	-- A 들어간거 다 찾기

SELECT * FROM EMPLOYEES
 WHERE  PHONE_NUMBER LIKE '___.127.____';

SELECT * FROM EMPLOYEES
 WHERE JOB_ID LIKE '%#____' ESCAPE '#';

SELECT * FROM EMPLOYEES
 WHERE JOB_ID LIKE '%\____' ESCAPE '\';

SELECT * FROM EMPLOYEES
 WHERE JOB_ID LIKE '%&____' ESCAPE '&';
 

SELECT EMPLOYEE_ID
	, FIRST_NAME
	, LAST_NAME
	, COMMISSION_PCT
  FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NULL;
 
SELECT EMPLOYEE_ID
	, FIRST_NAME
	, LAST_NAME
	, COMMISSION_PCT
  FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NOT NULL;